import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, Bot, Search, BrainCircuit, Download, Save } from 'lucide-react';
import { callLMStudio } from '../../config/lmStudio';
import { NeoMarkdown } from '../../components/ui/NeoMarkdown';
import { Magnetic } from '../../components/ui/Magnetic';

export const ToolAISalaryPredictor = ({ isAr, setPage, userContext, userProfile, setUserProfile, onSaveProfile, showToast, onCheckPoints, onDeductPoints }) => {
  const [major, setMajor] = useState(userProfile.careerPersona || '');
  const [skills, setSkills] = useState('');
  const [region, setRegion] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [thinkingSteps, setThinkingSteps] = useState([]);
  const [aiReport, setAiReport] = useState('');

  const saveReport = async (title, content) => {
    if (!userProfile.isLoggedIn) {
      showToast(isAr ? 'يجب تسجيل الدخول لحفظ التقارير!' : 'You must be logged in to save reports!');
      return;
    }
    
    try {
      const appId = 'masari-academic-decoder';
      const { getFirestore, collection, addDoc } = await import('firebase/firestore');
      const { getAuth } = await import('firebase/auth');
      const firestore = getFirestore();
      const auth = getAuth();
      const user = auth.currentUser;
      if (!user) throw new Error("No user object");

      const docData = {
        title,
        content,
        date: new Date().toISOString(),
      };
      
      const reportsRef = collection(firestore, 'artifacts', appId, 'users', user.uid, 'saved_reports');
      await addDoc(reportsRef, docData);
      
      showToast(isAr ? 'تم حفظ التقرير بنجاح! تجده في قائمة تقاريرك.' : 'Report saved to your artifacts successfully!');
    } catch(e) {
      console.error(e);
      showToast(isAr ? 'حدث خطأ أثناء حفظ التقرير.' : 'Error saving report.');
    }
  };

  const executeLiveSearch = async () => {
    if (!major.trim() || !region.trim()) {
      showToast(isAr ? 'يرجى إدخال التخصص والمنطقة المستهدفة' : 'Please input the major and target region');
      return;
    }

    if (onCheckPoints && !onCheckPoints(15)) {
      return;
    }

    setIsSearching(true);
    setThinkingSteps([]);
    setAiReport('');

    const steps = isAr ? [
      "تحديد الكيانات الرئيسية وأقطاب التخصص...",
      "بدء وكيل بحث الويب عبر الإضافات...",
      "تجميع الإحصائيات الفورية والتحقق من الوظائف الحالية...",
      "صياغة التقرير المالي والمهني المدمج..."
    ] : [
      "Formulating semantic entities from Major & Target Region...",
      "Activating online web plugins to verify live salary curves...",
      "Extracting current live job opportunities...",
      "Structuring professional report with citations..."
    ];

    for (let i = 0; i < steps.length; i++) {
      setThinkingSteps(prev => [...prev, steps[i]]);
      await new Promise(resolve => setTimeout(resolve, 800));
    }

    const langInst = isAr 
      ? 'MUST WRITE ENTIRELY IN ARABIC. DO NOT USE ENGLISH.' 
      : 'MUST WRITE ENTIRELY IN ENGLISH. DO NOT USE ARABIC.';
    const systemInstruction = `You are an elite career intelligence expert at Masari. Search specific websites (e.g., site:glassdoor.com, site:payscale.com, site:salary.com) to look up current job openings and salary data. Provide an informative analysis about salaries and available positions in the target area. Use Markdown extensively. ${langInst}`;
    
    const userPrompt = `Search specific websites (e.g., site:glassdoor.com, site:payscale.com) to provide realistic salary ranges (in local currency) and a list of typical hiring institutions for someone who studied "${major}" with these skills: "${skills}" in "${region}". Use Markdown format.`;
    const fallback = isAr ? `### تقرير التقديرات لـ ${major} في ${region}\n\n* **نطاق الراتب المتوقع:** 4,500$ - 7,000$ شهرياً.\n* **مجالات التوظيف الشائعة:** شركات التقنية المحلية، والهيئات الكبرى.` : `### Estimation Report for ${major} in ${region}\n\n* **Expected Salary Range:** $4,500 - $7,000 per month.\n* **Typical Hiring Industries:** Local tech companies, major authorities.`;

    try {
      const content = await callLMStudio(systemInstruction, userPrompt, fallback, true); // useSearchPlugins = true
      
      const isFallback = content === fallback;
      if (!isFallback && onDeductPoints) {
        onDeductPoints(15);
      }
      
      setAiReport(content);
      showToast(isAr ? "تم إنشاء التقرير بواسطة الذكاء الاصطناعي المتصل بالإنترنت!" : "Report generated by Web Grounded AI!");
    } catch (e) {
      console.error(e);
      setAiReport(fallback);
    } finally {
      setIsSearching(false);
    }
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([aiReport], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `Salary_Report.txt`;
    document.body.appendChild(element); 
    element.click();
  };

  return (
    <div className="min-h-screen pt-32 px-6 pb-20 text-theme-primary">
      <div className="max-w-[1200px] mx-auto text-black bg-white border-4 border-black p-8 md:p-12 rounded-[2.5rem] shadow-brutal">
        <button onClick={() => setPage(`dashboard_${userContext}`)} className="clickable-card mb-12 flex items-center gap-2 font-bold hover:text-[var(--accent-coral)] transition-colors">
          {isAr ? <ArrowRight className="w-5 h-5"/> : <ArrowLeft className="w-5 h-5"/>} 
          {isAr ? 'العودة للأدوات' : 'Back to Tools'}
        </button>

        <div className="mb-12">
          <h2 className="text-5xl md:text-6xl mb-4 font-display-en font-black">
            {isAr ? 'البحث العميق عن الرواتب المتوقعة والوظائف' : 'DeepSearch Expected Salary & Jobs'}
          </h2>
          <p className="text-xl opacity-70">
            {isAr ? 'تنفيذ استعلامات دلالية في الوقت الفعلي لاستهداف اتجاهات الرواتب بدقة والوظائف الشاغرة الحالية عبر إضافات الويب.' : 'Execute real-time queries targeting exact salary trends and current job openings via web plugins.'}
          </p>
        </div>

        <div className="grid lg:grid-cols-12 gap-12 text-black">
          
          <div className="lg:col-span-5 bg-theme-primary p-8 rounded-[2rem] border-4 border-black shadow-brutal space-y-6">
            <div>
              <label className="font-bold block mb-2">{isAr ? 'التخصص المدروس / المجال' : 'Major Studied / Domain'}</label>
              <input 
                type="text" value={major} onChange={e => setMajor(e.target.value)}
                placeholder={isAr ? 'مثل: علوم الحاسب' : 'e.g. Computer Science'}
                className="w-full bg-white border-4 border-black p-4 rounded-xl font-bold"
              />
            </div>

            <div>
              <label className="font-bold block mb-2">{isAr ? 'المهارات الأساسية (مفصولة بفاصلة)' : 'Core Skills (Comma separated)'}</label>
              <input 
                type="text" value={skills} onChange={e => setSkills(e.target.value)}
                placeholder={isAr ? 'مثل: بايثون، قواعد البيانات، إدارة المشاريع' : 'e.g. Python, SQL, Project Management'}
                className="w-full bg-white border-4 border-black p-4 rounded-xl font-bold"
              />
            </div>

            <div>
              <label className="font-bold block mb-2">{isAr ? 'المنطقة / البلد المستهدف' : 'Target Region / Country'}</label>
              <input 
                type="text" value={region} onChange={e => setRegion(e.target.value)}
                placeholder={isAr ? 'مثل: الرياض، المملكة العربية السعودية' : 'e.g. Riyadh, Saudi Arabia'}
                className="w-full bg-white border-4 border-black p-4 rounded-xl font-bold"
              />
            </div>

            <Magnetic strength={0.2} className="w-full">
              <button 
                onClick={executeLiveSearch} disabled={isSearching}
                className="w-full py-5 bg-[var(--accent-yellow)] text-black border-4 border-black rounded-xl font-black text-xl flex items-center justify-center gap-3 hover:bg-black hover:text-white transition-colors disabled:opacity-50"
              >
                <Search className="w-6 h-6 animate-pulse" />
                {isSearching ? (isAr ? 'جاري البحث في الأسواق...' : 'AI Searching Markets...') : (isAr ? 'البحث العميق عن الوظائف والرواتب' : 'DeepSearch Jobs & Salary')}
              </button>
            </Magnetic>
          </div>

          <div className="lg:col-span-7 bg-theme-primary p-8 rounded-[2rem] border-4 border-black shadow-brutal flex flex-col justify-start min-h-[400px]">
            {isSearching && (
              <div className="space-y-6">
                <h4 className="font-black text-xl text-[var(--accent-coral)] flex items-center gap-2">
                  <Bot className="w-6 h-6 animate-bounce" />
                  {isAr ? 'المساعد يقوم بمعالجة بحث الويب:' : 'Agent Processing Web Search:'}
                </h4>
                <div className="space-y-3">
                  {thinkingSteps.map((step, idx) => (
                    <div key={idx} className="flex items-center gap-3 font-bold text-lg bg-white border-2 border-black p-4 rounded-xl animate-pulse">
                      <span className="w-3 h-3 bg-green-500 rounded-full"></span>
                      <span>{step}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {!isSearching && !aiReport && (
              <div className="flex flex-col items-center justify-center text-center py-20 opacity-40">
                <BrainCircuit className="w-32 h-32 text-black mb-6 animate-pulse" />
                <h3 className="text-2xl font-black">{isAr ? 'في انتظار الإدخال لبدء الاستخراج المستند إلى الويب' : 'Awaiting Input to Trigger Grounded Scrapes'}</h3>
              </div>
            )}

            {aiReport && (
              <div className="page-enter text-black space-y-6">
                <div className="p-4 bg-[var(--accent-mint)] border-2 border-black rounded-2xl font-black flex items-center gap-2 text-sm justify-between shadow-[2px_2px_0_#000]">
                  <span>🚀 {isAr ? 'تم التحقق من التقرير باستخدام بيانات الويب الحية' : 'Report validated with live web data'}</span>
                  <div className="w-2.5 h-2.5 bg-green-500 rounded-full animate-ping"></div>
                </div>
                
                <NeoMarkdown text={aiReport} />

                <div className="mt-12 flex flex-col sm:flex-row gap-4 justify-center border-t-4 border-black pt-8">
                  <button onClick={handleDownload} className="py-4 px-6 bg-black text-white font-bold rounded-xl flex items-center justify-center gap-2 hover:bg-gray-800 transition-colors shadow-brutal-hover">
                    <Download className="w-5 h-5" />
                    {isAr ? 'تنزيل ملف نصي' : 'Download Txt'}
                  </button>
                  <button onClick={() => saveReport(isAr ? `الراتب: ${major}` : `Salary: ${major}`, aiReport)} className="py-4 px-6 bg-[var(--accent-mint)] border-2 border-black font-bold rounded-xl flex items-center justify-center gap-2 hover:bg-[var(--accent-lilac)] transition-colors shadow-brutal-hover">
                    <Save className="w-5 h-5" />
                    {isAr ? 'حفظ في التقارير' : 'Save to Artifacts'}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
